// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc7EJqI0Hyh2gLRS3pR9RrFpLerJ6v0yQ',
    appId: '1:870694041665:web:ba1e4fc87ab812e83d2ec0',
    messagingSenderId: '870694041665',
    projectId: 'leadbook-2d3d4',
    authDomain: 'leadbook-2d3d4.firebaseapp.com',
    storageBucket: 'leadbook-2d3d4.appspot.com',
    measurementId: 'G-GPKW4RXDDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0hLXUUS17ZmEJkHDoQfjFUQGLYgez7kc',
    appId: '1:870694041665:android:1290d5f8fd20f07f3d2ec0',
    messagingSenderId: '870694041665',
    projectId: 'leadbook-2d3d4',
    storageBucket: 'leadbook-2d3d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH7nGeSSlWujVUIefbN1Gmk3smbUz38cQ',
    appId: '1:870694041665:ios:667fad7af5e9aef93d2ec0',
    messagingSenderId: '870694041665',
    projectId: 'leadbook-2d3d4',
    storageBucket: 'leadbook-2d3d4.appspot.com',
    iosClientId: '870694041665-f9seeuk36comriil2ovj0sq14bos1fcs.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchetructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH7nGeSSlWujVUIefbN1Gmk3smbUz38cQ',
    appId: '1:870694041665:ios:17c6079771de12e33d2ec0',
    messagingSenderId: '870694041665',
    projectId: 'leadbook-2d3d4',
    storageBucket: 'leadbook-2d3d4.appspot.com',
    iosClientId: '870694041665-0qf834ov4agsddc195sdljrghkqppl89.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanArchitecture',
  );
}
